server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  mail:
    host: stmp.gmail.com
    port: 587
    username :
    password :
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/massage?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: asdf1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #show-sql:true
      format_sql: true

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  profiles:
    active: oauth

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG